config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'posts#index'

  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_votable
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  acts_as_votable

  scope :most_recent, -> (page_num) { order(created_at: :desc).limit(20).offset((page_num.to_i * 20) - 20)}

# scope :search, -> (search_parameter) { select("posts.id, posts.titles, posts.content, user.username as username").joins(:user).where("username like ?", "%#{search_parameter}%")}
# Post.joins(:user).where(users: {username: "Harwin"})
  scope :search, -> (search_parameter) { joins(:user).where("lower(title) like lower(?) OR lower(content) like lower(?) OR lower(users.username) like lower(?)", "%#{search_parameter}%", "%#{search_parameter}%", "%#{search_parameter}%")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

## THIS IS KEY FOR LOGGING IN WITH USERNAME INSTEAD OF EMAIL:
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment successfully added!"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def upvote
    @comment= Comment.find(params[:id])
    @comment.upvote_by current_user
    @comments = Comment.all
    redirect_to post_comments_path
  end

  def downvote
    @comment = Comment.find(params[:id])
    @comment.downvote_by current_user
    @comments = Comment.all
    redirect_to post_comments_path
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.most_recent(params[:page]) if params[:page].present?
    @posts = Post.most_recent(1) if !params[:page].present?
    @posts = @posts.search(params[:search]) if params[:search].present?
  end

  def new
    @post = Post.new
  end

def create
  @post = Post.new(post_params)
  if @post.save
    flash[:notice] = "Post successfully added!"
    redirect_to posts_path
  else
    render :new
  end
end

def show
  @post = Post.find(params[:id])
  @comments = @post.comments
  # @comment = @post.comments.new

end

def upvote
  @post= Post.find(params[:id])
  @post.upvote_by current_user
  @posts = Post.all
  redirect_to :posts
end

def downvote
  @post = Post.find(params[:id])
  @post.downvote_by current_user
  @posts = Post.all
  redirect_to :posts
end

private
  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1><%= @post.title %></h1>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.hidden_field(:user_id, :value => current_user.id) %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FanPage</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <ul class="nav justify-content-end bg-light">
    <% if current_user %>
      <li class="nav-item">
        <p class="nav-link">Welcome <%=current_user.username%></p>
      </li>
    <%end%>
    <li class="nav-item">
      <a class="nav-link active" href="/">Home</a>
    </li>
    <li class="nav-item ">
      <% if current_user %>
        <p class="nav-link"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></p>
      <% else %>
      <p class="nav-link"><%= link_to('Login', new_user_session_path)  %></p>
      <% end %>
    </li>
    <%= form_tag(posts_path, :method => "get", :class => "form-inline") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
      <%= submit_tag "Search" %>
    <% end %>
  </ul>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<%if @posts.length > 0 %>
<a href="?page=<%= params[:page] ? params[:page].to_i + 1 : 2 %>">Next Page</a>
<% end %>
<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %><br>Started: <%=post.created_at.strftime("%m/%d/%Y") %><br>- <%=post.user.username%></li>
    <%= link_to like_post_path(post), method: :put do %>
      <%= image_tag "up.png", :class => "icon" %>
      <%= post.get_upvotes.size %>
    <% end %>
    <%= link_to dislike_post_path(post), method: :put do %>
      <%= image_tag "down.png", :class => "icon" %>
      <%= post.get_downvotes.size %>
      <% end %>
  <% end %>
</ul>

<% if !current_user %>
  <h1>Please Log in to Post</h1>
  <h2><%= link_to('Login', new_user_session_path)  %></h2>
  <h2><%= link_to('Register', new_user_registration_path)  %></h2>
<% else %>
  <h1><%= link_to "New Post", new_post_path %></h1>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for [@post] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :content %><br>
  <%= f.text_area :content %><br>
  <%= f.hidden_field(:user_id, :value => current_user.id) %>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.user.username %></p>

<p><%= @post.content %></p>

<% if @comments.any? %>
  <% @comments.each do |comment| %>

  <div class='card mb-3 bg-secondary'>
    <div class='card-body'>
      <p><%=comment.content %></p>
      <p> - <%= comment.user.username %></p>
    </div>
  </div>
  <%end%>
  <%= link_to 'Add a comment', new_post_comment_path(@post) %>
<%else%>
  <%= link_to 'Make a comment, taint nun!', new_post_comment_path(@post) %>
<%end%>